# Makefile for gaknot project

# Default shell
SHELL := /bin/bash

# Find Sage sources while excluding editor and notebook checkpoint artifacts.
SAGE_FILES := $(shell find src/gaknot -name "*.sage" -not -path "*/.ipynb_checkpoints/*")
# Define the corresponding .py files
PY_FILES := $(patsubst %.sage,%.py,$(SAGE_FILES))

.PHONY: test benchmark_signature clean prep_commit check_env install build

# Check that a Sage installation is available. The recommended Conda
# environment is named sage_env, but native and differently named Sage
# environments are supported as well.
check_env:
	@if ! command -v sage >/dev/null 2>&1; then \
		echo "Error: SageMath is not available on PATH."; \
		echo "Activate a Sage environment, for example: conda activate sage_env"; \
		exit 1; \
	fi

# Rule to convert .sage to .py
src/gaknot/%.py: src/gaknot/%.sage
	sage --preparse $<
	mv $<.py $@

# Build target to ensure all .sage files are preparsed
build: check_env $(PY_FILES)
	@echo "Build complete: All .sage files preparsed to .py"

# Install the package in editable mode for development
install: build
	sage -pip install -e ".[test]"

# Run all standard Python tests in the tests/ directory
test: build
	PYTHONPATH=src sage -python -m pytest tests/

# Run performance measurements separately from correctness tests. The benchmark
# reports timings but deliberately imposes no machine-dependent pass/fail limit.
benchmark_signature: build
	PYTHONPATH=src sage -python benchmarks/benchmark_signature.py

# Remove autogenerated .py files and __pycache__
clean:
	find src/gaknot -name "*.py" -not -name "__init__.py" -not -name "utility.py" -not -name "clean.py" -delete
	find src/gaknot -name "__pycache__" -type d -exec rm -rf {} +
	find tests -name "__pycache__" -type d -exec rm -rf {} +
	find . -name "*.pyc" -delete

# Perform all pre-commit cleanup steps
prep_commit: clean
	@echo "Pre-commit cleanup complete."
