# Makefile for gaknot project

# Default shell
SHELL := /bin/bash

.PHONY: test clean clear_notebooks prep_commit check_env install

# Check if the correct conda environment is active
check_env:
	@if [ "$$CONDA_DEFAULT_ENV" != "sage_env" ]; then \
		echo "Error: 'sage_env' is not active."; \
		echo "Please run: conda activate sage_env"; \
		exit 1; \
	fi

# Install the package in editable mode for development
install: check_env
	pip install -e .

# Run all tests in notebooks
test: check_env
	cd tests && make test_all

# Remove autogenerated .py files from .sage files in src/gaknot/
clean: check_env
	cd src/gaknot && python3 clean.py

# Clear cell outputs in all Jupyter notebooks
clear_notebooks: check_env
	jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace tests/notebooks/*.ipynb

# Perform all pre-commit cleanup steps
prep_commit: check_env clean clear_notebooks
	@echo "Pre-commit cleanup complete."
