# Makefile for gaknot project

# Default shell
SHELL := /bin/bash

# Find all .sage files recursively in src/gaknot
SAGE_FILES := $(shell find src/gaknot -name "*.sage")
# Define the corresponding .py files
PY_FILES := $(patsubst %.sage,%.py,$(SAGE_FILES))

.PHONY: test clean prep_commit check_env install build

# Check if the correct conda environment is active
check_env:
	@if [ "$$GITHUB_ACTIONS" == "true" ] || [ "$$GITLAB_CI" == "true" ]; then \
		echo "Running in CI environment, bypassing environment check."; \
	elif [ "$$CONDA_DEFAULT_ENV" != "sage_env" ]; then \
		echo "Error: 'sage_env' is not active."; \
		echo "Please run: conda activate sage_env"; \
		exit 1; \
	fi

# Rule to convert .sage to .py
src/gaknot/%.py: src/gaknot/%.sage
	sage --preparse $<
	mv $<.py $@

# Build target to ensure all .sage files are preparsed
build: check_env $(PY_FILES)
	@echo "Build complete: All .sage files preparsed to .py"

# Install the package in editable mode for development
install: build
	sage -pip install -e .

# Run all standard Python tests in the tests/ directory
test: build
	PYTHONPATH=src sage -python -m pytest tests/

# Remove autogenerated .py files and __pycache__
clean: check_env
	find src/gaknot -name "*.py" -not -name "__init__.py" -not -name "utility.py" -not -name "clean.py" -delete
	find src/gaknot -name "__pycache__" -type d -exec rm -rf {} +
	find tests -name "__pycache__" -type d -exec rm -rf {} +
	find . -name "*.pyc" -delete

# Perform all pre-commit cleanup steps
prep_commit: clean
	@echo "Pre-commit cleanup complete."
