name: CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:latest
      options: --user root
    env:
      MPLBACKEND: Agg
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Testing Dependencies
        run: |
          sage -pip install ipytest pytest nbmake nbconvert ipykernel
          # Register the Sage kernel
          sage -python -m ipykernel install --user --name sagemath --display-name "SageMath"

      - name: Preparse Sage files
        run: |
          # Core
          cd src/gaknot/core
          for f in *.sage; do sage --preparse "$f" && mv "$f.py" "${f%.sage}.py"; done
          
          # Invariants
          cd ../invariants
          for f in *.sage; do sage --preparse "$f" && mv "$f.py" "${f%.sage}.py"; done

      - name: Run Tests in Notebooks
        run: |
          # Add src to PYTHONPATH so the tests can find 'gaknot'
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          sage -python -m pytest --nbmake tests/notebooks/*.ipynb --nbmake-kernel=sagemath
